export const states = [
  {"name":"Piemonte","value":"Piemonte","stationcount":"0"},
  {"name":"Valle d'Aosta","value":"Valle d'Aosta","stationcount":"0"},
  {"name":"Lombardia","value":"Lombardia","stationcount":"0"},
  {"name":"Trentino-Alto Adige/S\u00fcdtirol","value":"Trentino-Alto Adige/Südtirol","stationcount":"0"},
  {"name":"Veneto","value":"Veneto","stationcount":"0"},
  {"name":"Friuli-Venezia Giulia","value":"Friuli-Venezia Giulia","stationcount":"0"},
  {"name":"Liguria","value":"Liguria","stationcount":"0"},
  {"name":"Emilia-Romagna","value":"Emilia-Romagna","stationcount":"0"},
  {"name":"Toscana","value":"Toscana","stationcount":"0"},
  {"name":"Marche","value":"Marche","stationcount":"0"},
  {"name":"Umbria","value":"Umbria","stationcount":"0"},
  {"name":"Abruzzo","value":"Abruzzo","stationcount":"0"},
  {"name":"Molise","value":"Molise","stationcount":"0"},
  {"name":"Lazio","value":"Lazio","stationcount":"0"},
  {"name":"Campania","value":"Campania","stationcount":"0"},
  {"name":"Puglia","value":"Puglia","stationcount":"0"},
  {"name":"Basilicata","value":"Basilicata","stationcount":"0"},
  {"name":"Calabria","value":"Calabria","stationcount":"0"},
  {"name":"Sicilia","value":"Sicilia","stationcount":"0"},
  {"name":"Sardegna","value":"Sardegna","stationcount":"0"}
]